In [2]:
import numpy as np
import pandas as pd
from pylab import plt
import scipy.optimize as sco
plt.style.use("ggplot")

In [3]:
def find_covariance_matrix(corr, st_dev):
    n = len(st_dev)
    cov_matrix = np.zeros((n, n))
    
    # Indexing the correlations based on the provided order [ρ12, ρ23, ρ13]
    corr_index = { (0, 1): 0, (1, 2): 1, (0, 2): 2 }
    
    # Fill the upper triangle and the lower triangle symmetrically
    for i in range(n):
        for j in range(i + 1, n):
            rho = corr[corr_index[(i, j)] if (i, j) in corr_index else corr_index[(j, i)]]
            cov_matrix[i, j] = rho * st_dev[i] * st_dev[j]
            cov_matrix[j, i] = cov_matrix[i, j]

    # Fill the diagonal
    for i in range(n):
        cov_matrix[i, i] = st_dev[i] ** 2

    return cov_matrix

def invert_matrix(matrix):
    return np.linalg.inv(matrix)

In [4]:
expected_returns = [0.15, -0.1, 0.1]
standard_deviations = [0.2, 0.15, 0.1]
correlations = [0.3, -0.1, 0.2]

In [5]:
cov_mat = find_covariance_matrix(correlations, standard_deviations)
cov_mat_inv = invert_matrix(cov_mat)

print(cov_mat)
print("\n")
print(cov_mat_inv)

[[ 0.04    0.009   0.004 ]
 [ 0.009   0.0225 -0.0015]
 [ 0.004  -0.0015  0.01  ]]


[[ 29.18632075 -12.57861635 -13.56132075]
 [-12.57861635  50.31446541  12.57861635]
 [-13.56132075  12.57861635 107.31132075]]


In [6]:
initial_weights = np.ones(standard_deviations)
print(initial_weights)

TypeError: 'float' object cannot be interpreted as an integer